name: budget_planner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.10
  cool_dropdown: ^2.1.0
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0+1
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  firebase_storage: ^11.6.11
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  intl_phone_number_field: ^0.1.9
  logger: ^2.2.0
  pinput: ^4.0.0
  provider: ^6.1.2
  unique_simple_bar_chart: ^0.0.4
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   intl_phone_number_field:
#     path: ..
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/countries/
    - assets/background/
    - assets/components/
    - assets/transactions/
